### ISSUE TITLE
fluxctl: automate updates

### ISSUE THREAD

**Issue by dholbach** [weaveworks/homebrew-tap#2]
[fluxctl](https://github.com/weaveworks/homebrew-tap/blob/master/Formula/fluxctl.rb) was integrated into `homebrew-tap`. Right now it's a one-off though, it will need manual updating for a new release. It'd be great if it could be hooked up with something like go-releaser (used in eksctl, c.f. [1](https://github.com/weaveworks/eksctl/blob/master/.goreleaser.brew.yml), [2](https://github.com/weaveworks/eksctl/blob/master/.goreleaser.yml)).

**Comment by dholbach** [comment]
Another option would be to try to get into https://github.com/Homebrew/homebrew-core/tree/master/Formula

**Comment by dholbach** [comment]
cc @squaremo (jfyi)

**Comment by errordeveloper** [comment]
> - continue to just download the darwin64 binary as opposed to building from source

No, we will have to rewrite to build from source.

> - require us to update the formula with new url and sha for every `flux` release (not sure if we can automate a PR easily)

Tag and revision, not the checksum, see https://github.com/Homebrew/homebrew-core/commit/4f0f2556e4e92c305ccbb1c24ae6bacdad464fb9. 

I think PR bot would be easy to implement, the chances are there is a bot that we can adopt (or, adapt, if you like).

> - be more easy to find

Yes, so much so!

**Comment by dholbach** [comment]
Does
```ruby
class Fluxctl < Formula
  desc "fluxctl talks to Weave Flux and helps you deploy your code"
  homepage "https://github.com/weaveworks/flux"
  url "https://github.com/weaveworks/flux.git",
      :tag => "1.6.0",
      :revision => "f304fbeeff36672f9b43de132e7ede676b25a737"
  head "https://github.com/weaveworks/flux.git"

  bottle do
    cellar :any_skip_relocation
    sha256 "d00a240d03a1de64df9d76df58855385638d0abdfdad09d2f88c2140a6178d75" => :mojave
    sha256 "e1859f9f893237aa977be328846481b362e147ae92c2cde3e65a7d445b02dae9" => :high_sierra
    sha256 "5752d5baff35437176ac169469fdc27e2bcb740da74ebbf3191ddbb009c23941" => :sierra
    sha256 "67e7ad04098e52028d5d9e8f32fe9c530778be555842c6cf1ad39839945d312b" => :el_capitan
  end

  depends_on "dep" => :build
  depends_on "go" => :build

  def install
    ENV["GOPATH"] = buildpath
    arch = MacOS.prefer_64_bit? ? "amd64" : "x86"
    dir = buildpath/"src/github.com/weaveworks/flux"
    dir.install buildpath.children - [buildpath/".brew_home"]

    cd dir do
      system "dep", "ensure"
      system "dep", "prune"
      
      # Make binary
      system "go", "build", "./cmd/fluxctl"
      bin.install "fluxctl"

      prefix.install_metafiles
    end
  end

  test do
    run_output = shell_output("#{bin}/fluxctl 2>&1")
    assert_match "fluxctl helps you deploy your code.", run_output
  end
end
```
work for you?

**Comment by foot** [comment]
My output from testing!: ```
newq:~/src/tmp$ brew install fluxctl.rb
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> New Formulae
nwchem                                                                                                                                                                                                               smimesign
==> Updated Formulae
aurora-cli                                           carla                                                git-lfs                                              jfrog-cli-go                                         jhipster                                             prototool                                            vala                                                 youtube-dl

==> Downloading https://homebrew.bintray.com/bottles/fluxctl-1.6.0.high_sierra.bottle.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "fluxctl"
Download failed: https://homebrew.bintray.com/bottles/fluxctl-1.6.0.high_sierra.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Cloning https://github.com/weaveworks/flux.git
Cloning into '/Users/simon/Library/Caches/Homebrew/fluxctl--git'...
Note: checking out 'f304fbeeff36672f9b43de132e7ede676b25a737'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

==> Checking out tag 1.6.0
HEAD is now at f304fbe Merge pull request #1329 from weaveworks/release/v1.6.0
==> dep ensure
==> dep prune
==> go build ./cmd/fluxctl
🍺  /usr/local/Cellar/fluxctl/1.6.0: 6 files, 34.0MB, built in 3 minutes 54 seconds
```

**Comment by dholbach** [comment]
So the build seems to work, that's great - the binary installs and runs fine as well.

Unfortunately I haven't quite figured out how the [bottle machinery](https://docs.brew.sh/Bottles) works. The current sha256sums are wrong, so they'd need updating before this is submitted to homebrew.

**Comment by errordeveloper** [comment]
Daniel, bottling is automated by a bot. You will need to remove the
checksums completely. See kops and kubernetes-cli formulas for reference.

**Comment by dholbach** [comment]
Ok. I had a look at the `kops` formula where the bottle section was not part of what was initially proposed. Does the following look good to propose to `homebrew-core`?

```ruby
class Fluxctl < Formula
  desc "fluxctl talks to Weave Flux and helps you deploy your code"
  homepage "https://github.com/weaveworks/flux"
  url "https://github.com/weaveworks/flux.git",
      :tag => "1.7.0",
      :revision => "a41dd3821ac05c90efe123659c2bd364d2299026"
  head "https://github.com/weaveworks/flux.git"

  depends_on "dep" => :build
  depends_on "go" => :build

  def install
    ENV["GOPATH"] = buildpath
    arch = MacOS.prefer_64_bit? ? "amd64" : "x86"
    dir = buildpath/"src/github.com/weaveworks/flux"
    dir.install buildpath.children - [buildpath/".brew_home"]

    cd dir do
      system "dep", "ensure"
      system "dep", "prune"
      
      # Make binary
      system "go", "build", "./cmd/fluxctl"
      bin.install "fluxctl"

      prefix.install_metafiles
    end
  end

  test do
    run_output = shell_output("#{bin}/fluxctl 2>&1")
    assert_match "fluxctl helps you deploy your code.", run_output
  end
end
```

**Comment by dholbach** [comment]
Submitted this to `homebrew-core`.
