### ISSUE TITLE
brew tap weaveworks/tap fails

### ISSUE THREAD

**Issue by ericmason** [weaveworks/homebrew-tap#22]
Looks like `head` was added without quoting [today](https://github.com/weaveworks/homebrew-tap/commit/0128bab21fab969775b8f4ca0acb97f39450e845#diff-be7af79d0166963e1fc4c3b65f173d83)

```
==> Tapping weaveworks/tap
Cloning into '/usr/local/Homebrew/Library/Taps/weaveworks/homebrew-tap'...
remote: Enumerating objects: 97, done.
remote: Counting objects: 100% (97/97), done.
remote: Compressing objects: 100% (94/94), done.
remote: Total 501 (delta 39), reused 11 (delta 3), pack-reused 404
Receiving objects: 100% (501/501), 72.21 KiB | 1.60 MiB/s, done.
Resolving deltas: 100% (185/185), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/weaveworks/homebrew-tap/Formula/eksctl-private.rb
eksctl-private: /usr/local/Homebrew/Library/Taps/weaveworks/homebrew-tap/Formula/eksctl-private.rb:15: unknown regexp options - gthb
Error: Cannot tap weaveworks/tap: invalid syntax in tap!
```

**Comment by ChaimCode** [comment]
This commit (58e08779d2d59bc1e099af2e7a166d458341fec5) is reason. I just revert and solve this problem.

**Comment by ChaimCode** [comment]
> Looks like `head` was added without quoting [today](https://github.com/weaveworks/homebrew-tap/commit/0128bab21fab969775b8f4ca0acb97f39450e845#diff-be7af79d0166963e1fc4c3b65f173d83)
> 
> ```
> ==> Tapping weaveworks/tap
> Cloning into '/usr/local/Homebrew/Library/Taps/weaveworks/homebrew-tap'...
> remote: Enumerating objects: 97, done.
> remote: Counting objects: 100% (97/97), done.
> remote: Compressing objects: 100% (94/94), done.
> remote: Total 501 (delta 39), reused 11 (delta 3), pack-reused 404
> Receiving objects: 100% (501/501), 72.21 KiB | 1.60 MiB/s, done.
> Resolving deltas: 100% (185/185), done.
> Error: Invalid formula: /usr/local/Homebrew/Library/Taps/weaveworks/homebrew-tap/Formula/eksctl-private.rb
> eksctl-private: /usr/local/Homebrew/Library/Taps/weaveworks/homebrew-tap/Formula/eksctl-private.rb:15: unknown regexp options - gthb
> Error: Cannot tap weaveworks/tap: invalid syntax in tap!
> ```

This commit (58e0877) is reason. I just revert and solve this problem.

**Comment by jvergara-runbuggy** [comment]
It fails for me too.  I can not install eksctl via Homebrew.  Is there other way to install it while is this fixed?

**Comment by uchiumih** [comment]
@jvergara-runbuggy You can get eksctl from [releases](https://github.com/weaveworks/eksctl/releases) of eksctl repository.

**Comment by mxplusb** [comment]
I can confirm it's still happening today.

```
✓ brew tap weaveworks/tap
Updating Homebrew...
==> Tapping weaveworks/tap
Cloning into '/usr/local/Homebrew/Library/Taps/weaveworks/homebrew-tap'...
remote: Enumerating objects: 113, done.
remote: Counting objects: 100% (113/113), done.
remote: Compressing objects: 100% (110/110), done.
remote: Total 517 (delta 47), reused 11 (delta 3), pack-reused 404
Receiving objects: 100% (517/517), 74.25 KiB | 1.43 MiB/s, done.
Resolving deltas: 100% (193/193), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/weaveworks/homebrew-tap/Formula/eksctl-private.rb
eksctl-private: /usr/local/Homebrew/Library/Taps/weaveworks/homebrew-tap/Formula/eksctl-private.rb:15: unknown regexp options - gthb
Error: Cannot tap weaveworks/tap: invalid syntax in tap!
```

**Comment by kingdonb** [comment]
This issue is no longer present. (from the eksctl-private formula):

```
  head "https://github.com/weaveworks/eksctl-private/releases/download/latest_release/eksctl_Darwin_amd64.tar.gz"
```
