### ISSUE TITLE
Update to 0.33

### ISSUE THREAD

**Issue by inductor** [weaveworks/homebrew-tap#27]
Hello, I want to use spot managed instance.

Can you update it to 0.33 now it's available?

**Comment by michaelbeaumont** [comment]
Hi, the tap points to the latest stable release. We will be doing a stable release shortly but for now we have only `0.33.0-rc.0`. You can however reinstall `eksctl` with homebrew, adding the `--HEAD` flag, to get the release candidate.

**Comment by inductor** [comment]
@michaelbeaumont 
No, It was already released when I created this issue
https://github.com/weaveworks/eksctl/releases/tag/0.33.0
