### ISSUE TITLE
eksctl.rb includes deprecated reference to "bottle :unneeded"

### ISSUE THREAD

**Issue by rherrick** [weaveworks/homebrew-tap#28]
I just started getting this message when running `brew upgrade`, `brew cleanup`, or  `brew doctor`:

```bash
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the weaveworks/tap tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/weaveworks/homebrew-tap/Formula/eksctl.rb:9
```

[Line 9 of eksctl.rb](https://github.com/weaveworks/homebrew-tap/blob/master/Formula/eksctl.rb#L9) is just this:

```ruby
bottle :unneeded
```

Deleting that line in my local Homebrew repo causes the warning to go away. I'd submit a pull request for the change but I can see that file is updated and committed by a bot, so I'm not sure if that file _is_ the source template with the `bottle` reference or if it's generated from somewhere else.

**Comment by max-synapse** [comment]
+1 same here

**Comment by rherrick** [comment]
This issue was fixed in a [PR that was merged to master](https://github.com/weaveworks/homebrew-tap/commit/e574ba7cd97bc236589fdbd4dc0c4688d2cc9c83) yesterday, but that change was [overwritten today](https://github.com/weaveworks/homebrew-tap/commit/e8120d59f1de3fe33ef42571a2014cfa9bef66d0) by @weaveworksbot.

**Comment by Skarlso** [comment]
@rherrick Ah. Thanks for finding that. We'll work on the bot.

**Comment by Himangini** [comment]
Related to https://github.com/weaveworks/eksctl/issues/4458
